### ISSUE TITLE
Pal spawning doesnt appear in the gui

### ISSUE THREAD

**Issue by N0SKILL-ai** [SoTMaulder/SoTMaulder-Palworld#3]
There is no option to spawn a pal in the gui

**Comment by SoTMaulder** [comment]
Yah that was patched a while ago

**Comment by bnthomason** [comment]
Can you readd this on a fork? I have version 0.1.2.0. Or else, how do I restore a fork?

Also, for some reason, I get an error message that complains in Visual Studio 2019 that it was built with v143 tools, and in Visual Studio 2022, it has compilation errors after upgrading the project to current toolset (unfortunately, I can't test the problem right now because Visual Studio is broken on both programs and a reinstall won't fix it.)
